name: Deploy Laravel Project to cPanel (FTP delta)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      
      - name: Upload via FTP (delta)
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}       
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp                          
          port: 21                                
          server-dir: /home/cp61664/filament.atenahadavi.com/
          local-dir: ./
          exclude: |
           **/.git*
            **/.github/**
            **/node_modules/**
            **/.env
            **/.DS_Store
            **/storage/logs/**
            **/storage/framework/cache/**
            **/storage/framework/sessions/**
            **/storage/framework/views/**
            **/storage/debugbar/**
            **/vendor/**
